-- A larger, varied pack so a room can play many matches without repeatedly
-- seeing the same answer. Terms are concrete, family-friendly, and drawable.

INSERT INTO words (word, category) VALUES
    -- Động vật
    ('con dê', 'ANIMALS'), ('con cừu', 'ANIMALS'), ('lạc đà', 'ANIMALS'),
    ('con lừa', 'ANIMALS'), ('bò tót', 'ANIMALS'), ('heo rừng', 'ANIMALS'),
    ('thỏ rừng', 'ANIMALS'), ('chuột chũi', 'ANIMALS'), ('con dơi', 'ANIMALS'),
    ('chó sói', 'ANIMALS'), ('con cáo', 'ANIMALS'), ('linh cẩu', 'ANIMALS'),
    ('gấu koala', 'ANIMALS'), ('gấu mèo', 'ANIMALS'), ('con vượn', 'ANIMALS'),
    ('đười ươi', 'ANIMALS'), ('khỉ đầu chó', 'ANIMALS'), ('chim ruồi', 'ANIMALS'),
    ('thiên nga', 'ANIMALS'), ('vịt trời', 'ANIMALS'), ('hải âu', 'ANIMALS'),
    ('chim gõ kiến', 'ANIMALS'), ('chim hồng hạc', 'ANIMALS'), ('rùa biển', 'ANIMALS'),
    ('kỳ đà', 'ANIMALS'), ('tắc kè hoa', 'ANIMALS'), ('bọ rùa', 'ANIMALS'),
    ('chuồn chuồn', 'ANIMALS'), ('bọ ngựa', 'ANIMALS'), ('ve sầu', 'ANIMALS'),
    ('bọ cạp', 'ANIMALS'), ('cua hoàng đế', 'ANIMALS'), ('tôm hùm', 'ANIMALS'),
    ('sò biển', 'ANIMALS'), ('sao biển', 'ANIMALS'), ('cá đuối', 'ANIMALS'),
    ('cá kiếm', 'ANIMALS'), ('cá nóc', 'ANIMALS'), ('cá vàng', 'ANIMALS'),
    ('con mực', 'ANIMALS'),

    -- Đồ ăn và thức uống
    ('phở gà', 'FOOD'), ('bánh mì thịt', 'FOOD'), ('cơm tấm', 'FOOD'),
    ('cơm chiên', 'FOOD'), ('cơm nắm', 'FOOD'), ('canh chua', 'FOOD'),
    ('nem rán', 'FOOD'), ('chả giò', 'FOOD'), ('bánh khọt', 'FOOD'),
    ('bánh dừa', 'FOOD'), ('bánh pía', 'FOOD'), ('bánh flan', 'FOOD'),
    ('bánh quy', 'FOOD'), ('bánh waffle', 'FOOD'), ('pizza', 'FOOD'),
    ('mì ramen', 'FOOD'), ('mì udon', 'FOOD'), ('sandwich', 'FOOD'),
    ('salad', 'FOOD'), ('bít tết', 'FOOD'), ('gà quay', 'FOOD'),
    ('cá nướng', 'FOOD'), ('tôm chiên', 'FOOD'), ('lẩu', 'FOOD'),
    ('súp', 'FOOD'), ('cháo lòng', 'FOOD'), ('đậu hũ', 'FOOD'),
    ('bắp luộc', 'FOOD'), ('khoai lang', 'FOOD'), ('dưa hấu', 'FOOD'),
    ('quả xoài', 'FOOD'), ('quả dâu', 'FOOD'), ('quả nho', 'FOOD'),
    ('quả lê', 'FOOD'), ('quả đào', 'FOOD'), ('trà sữa', 'FOOD'),
    ('nước chanh', 'FOOD'), ('ca cao nóng', 'FOOD'), ('sinh tố', 'FOOD'),
    ('kem que', 'FOOD'),

    -- Đồ vật
    ('cái búa', 'OBJECTS'), ('cái kìm', 'OBJECTS'), ('tua vít', 'OBJECTS'),
    ('cờ lê', 'OBJECTS'), ('máy khoan', 'OBJECTS'), ('cưa tay', 'OBJECTS'),
    ('cuộn băng keo', 'OBJECTS'), ('dây thừng', 'OBJECTS'), ('cái móc áo', 'OBJECTS'),
    ('cái xô', 'OBJECTS'), ('chậu cây', 'OBJECTS'), ('bình tưới cây', 'OBJECTS'),
    ('đồng hồ báo thức', 'OBJECTS'), ('ống nhòm', 'OBJECTS'), ('la bàn', 'OBJECTS'),
    ('kính thiên văn', 'OBJECTS'), ('máy ảnh', 'OBJECTS'), ('máy quay phim', 'OBJECTS'),
    ('máy tính tiền', 'OBJECTS'), ('máy hút bụi', 'OBJECTS'), ('bàn ủi', 'OBJECTS'),
    ('cái ô', 'OBJECTS'), ('áo phao', 'OBJECTS'), ('phao bơi', 'OBJECTS'),
    ('đèn lồng giấy', 'OBJECTS'), ('hộp cơm', 'OBJECTS'), ('cái muỗng', 'OBJECTS'),
    ('cái nĩa', 'OBJECTS'), ('đôi đũa', 'OBJECTS'), ('cái rổ', 'OBJECTS'),
    ('cái rá', 'OBJECTS'), ('giỏ mây', 'OBJECTS'), ('cái cân', 'OBJECTS'),
    ('cờ nhỏ', 'OBJECTS'), ('mô hình tên lửa', 'OBJECTS'), ('túi ngủ', 'OBJECTS'),
    ('đèn bàn', 'OBJECTS'), ('máy khâu', 'OBJECTS'), ('khung cửa', 'OBJECTS'),
    ('cái chuông', 'OBJECTS'),

    -- Địa điểm
    ('sân bay', 'PLACES'), ('trạm xăng', 'PLACES'), ('nhà thuốc', 'PLACES'),
    ('phòng khám', 'PLACES'), ('bệnh viện', 'PLACES'), ('thư viện', 'PLACES'),
    ('nhà sách', 'PLACES'), ('cửa hàng tiện lợi', 'PLACES'), ('siêu thị', 'PLACES'),
    ('nhà hàng', 'PLACES'), ('quán ăn', 'PLACES'), ('khách sạn', 'PLACES'),
    ('khu nghỉ dưỡng', 'PLACES'), ('công viên', 'PLACES'), ('vườn hoa', 'PLACES'),
    ('quảng trường', 'PLACES'), ('cầu cảng', 'PLACES'), ('hải đăng', 'PLACES'),
    ('sân golf', 'PLACES'), ('sân trượt băng', 'PLACES'), ('phòng tập gym', 'PLACES'),
    ('tiệm cắt tóc', 'PLACES'), ('tiệm giặt ủi', 'PLACES'), ('xưởng sửa xe', 'PLACES'),
    ('nhà máy', 'PLACES'), ('công trường', 'PLACES'), ('trang trại gió', 'PLACES'),
    ('vườn thú', 'PLACES'), ('thủy cung', 'PLACES'), ('công viên nước', 'PLACES'),
    ('phòng triển lãm', 'PLACES'), ('trung tâm thương mại', 'PLACES'),
    ('bãi đỗ xe', 'PLACES'), ('trạm thu phí', 'PLACES'), ('khu cắm trại', 'PLACES'),
    ('sân chơi', 'PLACES'), ('đài phun nước', 'PLACES'), ('tòa thị chính', 'PLACES'),
    ('tháp canh', 'PLACES'), ('cổng thành', 'PLACES'),

    -- Thiên nhiên
    ('cầu vồng', 'NATURE'), ('mây trắng', 'NATURE'), ('mây đen', 'NATURE'),
    ('gió mạnh', 'NATURE'), ('lốc xoáy', 'NATURE'), ('mưa đá', 'NATURE'),
    ('sương mù', 'NATURE'), ('băng trôi', 'NATURE'), ('sông băng', 'NATURE'),
    ('dòng sông', 'NATURE'), ('con suối', 'NATURE'), ('đầm lầy', 'NATURE'),
    ('bờ đá', 'NATURE'), ('vách núi', 'NATURE'), ('dãy núi', 'NATURE'),
    ('thung lũng', 'NATURE'), ('rừng tre', 'NATURE'), ('rừng thông', 'NATURE'),
    ('cây đa', 'NATURE'), ('cây dừa', 'NATURE'), ('cây phong', 'NATURE'),
    ('bông hướng dương', 'NATURE'), ('hoa hồng', 'NATURE'), ('hoa tulip', 'NATURE'),
    ('nấm rừng', 'NATURE'), ('hạt giống', 'NATURE'), ('quả thông', 'NATURE'),
    ('tổ ong', 'NATURE'), ('mạng nhện', 'NATURE'), ('bãi cát', 'NATURE'),
    ('sóng biển', 'NATURE'), ('thủy triều', 'NATURE'), ('giọt sương', 'NATURE'),
    ('nguyệt thực', 'NATURE'), ('nhật thực', 'NATURE'), ('dải ngân hà', 'NATURE'),
    ('hành tinh', 'NATURE'), ('sao chổi', 'NATURE'), ('mỏm đá', 'NATURE'),
    ('đồi cát', 'NATURE'),

    -- Công nghệ
    ('máy tính xách tay', 'TECHNOLOGY'), ('máy tính bảng', 'TECHNOLOGY'),
    ('màn hình cảm ứng', 'TECHNOLOGY'), ('webcam', 'TECHNOLOGY'), ('máy chiếu', 'TECHNOLOGY'),
    ('robot hút bụi', 'TECHNOLOGY'), ('robot đồ chơi', 'TECHNOLOGY'),
    ('cánh tay robot', 'TECHNOLOGY'), ('vệ tinh', 'TECHNOLOGY'), ('tên lửa', 'TECHNOLOGY'),
    ('trạm vũ trụ', 'TECHNOLOGY'), ('kính thiên văn không gian', 'TECHNOLOGY'),
    ('máy chơi game', 'TECHNOLOGY'), ('tay cầm chơi game', 'TECHNOLOGY'),
    ('máy arcade', 'TECHNOLOGY'), ('máy bán hàng tự động', 'TECHNOLOGY'),
    ('máy pha cà phê', 'TECHNOLOGY'), ('máy lọc không khí', 'TECHNOLOGY'),
    ('máy lọc nước', 'TECHNOLOGY'), ('camera an ninh', 'TECHNOLOGY'),
    ('chuông cửa thông minh', 'TECHNOLOGY'), ('khóa vân tay', 'TECHNOLOGY'),
    ('bản mạch điện tử', 'TECHNOLOGY'), ('bóng đèn led', 'TECHNOLOGY'),
    ('pin mặt trời', 'TECHNOLOGY'), ('tuabin gió', 'TECHNOLOGY'),
    ('cáp sạc', 'TECHNOLOGY'), ('wifi', 'TECHNOLOGY'), ('biểu tượng bluetooth', 'TECHNOLOGY'),
    ('mã qr', 'TECHNOLOGY'), ('bộ phát wifi', 'TECHNOLOGY'), ('thẻ nhớ', 'TECHNOLOGY'),
    ('bộ định tuyến', 'TECHNOLOGY'), ('máy tính để bàn', 'TECHNOLOGY'),
    ('đồng hồ kỹ thuật số', 'TECHNOLOGY'), ('máy đếm bước chân', 'TECHNOLOGY'),
    ('microphone phòng thu', 'TECHNOLOGY'), ('bảng điện tử', 'TECHNOLOGY'),
    ('máy in 3d', 'TECHNOLOGY'), ('cổng usb', 'TECHNOLOGY'),

    -- Giao thông
    ('xe jeep', 'TRANSPORT'), ('xe bán tải', 'TRANSPORT'), ('xe mui trần', 'TRANSPORT'),
    ('xe limousine', 'TRANSPORT'), ('xe buýt hai tầng', 'TRANSPORT'), ('xe nhà di động', 'TRANSPORT'),
    ('xe đạp đôi', 'TRANSPORT'), ('xe đạp điện', 'TRANSPORT'), ('xe một bánh', 'TRANSPORT'),
    ('xe lăn', 'TRANSPORT'), ('xe nôi', 'TRANSPORT'), ('xe cút kít', 'TRANSPORT'),
    ('xe chở kem', 'TRANSPORT'), ('xe chở thư', 'TRANSPORT'), ('xe bồn', 'TRANSPORT'),
    ('xe ủi', 'TRANSPORT'), ('xe lu', 'TRANSPORT'), ('xe xúc', 'TRANSPORT'),
    ('xe cần cẩu', 'TRANSPORT'), ('xe địa hình', 'TRANSPORT'), ('tàu điện ngầm', 'TRANSPORT'),
    ('tàu điện', 'TRANSPORT'), ('tàu cao tốc', 'TRANSPORT'), ('tàu chở hàng', 'TRANSPORT'),
    ('thuyền thúng', 'TRANSPORT'), ('thuyền kayak', 'TRANSPORT'), ('phà', 'TRANSPORT'),
    ('gondola', 'TRANSPORT'), ('xe trượt patin', 'TRANSPORT'), ('máy bay trực thăng', 'TRANSPORT'),
    ('phi thuyền', 'TRANSPORT'), ('tên lửa đẩy', 'TRANSPORT'), ('khí cầu', 'TRANSPORT'),
    ('dù lượn', 'TRANSPORT'), ('cáp treo', 'TRANSPORT'), ('xe goòng', 'TRANSPORT'),
    ('xe kéo hàng', 'TRANSPORT'), ('xe cứu hộ', 'TRANSPORT'), ('xe quét đường', 'TRANSPORT'),
    ('xe chở rác', 'TRANSPORT'),

    -- Thể thao
    ('đá bóng', 'SPORTS'), ('ném bóng', 'SPORTS'), ('bóng chày', 'SPORTS'),
    ('cricket', 'SPORTS'), ('khúc côn cầu', 'SPORTS'), ('bóng bầu dục', 'SPORTS'),
    ('bóng ném', 'SPORTS'), ('ném đĩa', 'SPORTS'), ('đấu kiếm', 'SPORTS'),
    ('judo', 'SPORTS'), ('karate', 'SPORTS'), ('taekwondo', 'SPORTS'),
    ('sumo', 'SPORTS'), ('đấu vật', 'SPORTS'), ('cử tạ', 'SPORTS'),
    ('đẩy tạ', 'SPORTS'), ('ném lao', 'SPORTS'), ('ném tạ', 'SPORTS'),
    ('chạy tiếp sức', 'SPORTS'), ('chạy marathon', 'SPORTS'), ('đạp xe', 'SPORTS'),
    ('đua thuyền', 'SPORTS'), ('chèo thuyền', 'SPORTS'), ('lặn biển', 'SPORTS'),
    ('bóng nước', 'SPORTS'), ('bơi nghệ thuật', 'SPORTS'), ('trượt tuyết', 'SPORTS'),
    ('trượt ván tuyết', 'SPORTS'), ('nhảy cầu', 'SPORTS'), ('nhảy dù', 'SPORTS'),
    ('bắn súng thể thao', 'SPORTS'), ('phi tiêu', 'SPORTS'), ('bi da', 'SPORTS'),
    ('golf', 'SPORTS'), ('đánh golf', 'SPORTS'), ('patin', 'SPORTS'),
    ('nhảy xa', 'SPORTS'), ('nhảy ba bước', 'SPORTS'), ('yoga', 'SPORTS'),
    ('aerobic', 'SPORTS'),

    -- Nghề nghiệp
    ('dược sĩ', 'PROFESSIONS'), ('nha sĩ', 'PROFESSIONS'), ('bác sĩ thú y', 'PROFESSIONS'),
    ('kỹ sư', 'PROFESSIONS'), ('thợ máy', 'PROFESSIONS'), ('thợ mộc', 'PROFESSIONS'),
    ('thợ hàn', 'PROFESSIONS'), ('thợ sửa ống nước', 'PROFESSIONS'), ('thợ làm bánh', 'PROFESSIONS'),
    ('thợ làm gốm', 'PROFESSIONS'), ('thợ may', 'PROFESSIONS'), ('thợ làm vườn', 'PROFESSIONS'),
    ('người giao hàng', 'PROFESSIONS'), ('nhân viên phục vụ', 'PROFESSIONS'),
    ('thu ngân', 'PROFESSIONS'), ('lễ tân', 'PROFESSIONS'), ('hướng dẫn viên', 'PROFESSIONS'),
    ('thủ thư', 'PROFESSIONS'), ('luật sư', 'PROFESSIONS'), ('thẩm phán', 'PROFESSIONS'),
    ('kế toán', 'PROFESSIONS'), ('nhân viên ngân hàng', 'PROFESSIONS'),
    ('nhà thiết kế thời trang', 'PROFESSIONS'), ('nhà thiết kế nội thất', 'PROFESSIONS'),
    ('biên tập viên', 'PROFESSIONS'), ('phát thanh viên', 'PROFESSIONS'),
    ('vũ công', 'PROFESSIONS'), ('ảo thuật gia', 'PROFESSIONS'), ('nhạc sĩ', 'PROFESSIONS'),
    ('nhà văn', 'PROFESSIONS'), ('nhà thơ', 'PROFESSIONS'), ('thợ lặn', 'PROFESSIONS'),
    ('kiểm lâm', 'PROFESSIONS'), ('người nuôi ong', 'PROFESSIONS'),
    ('thuyền trưởng', 'PROFESSIONS'), ('tiếp viên hàng không', 'PROFESSIONS'),
    ('nhà khảo cổ', 'PROFESSIONS'), ('nhà thiên văn học', 'PROFESSIONS'),
    ('nhà khí tượng học', 'PROFESSIONS'), ('đội trưởng bóng đá', 'PROFESSIONS'),

    -- Học đường
    ('bàn học', 'SCHOOL'), ('ghế học sinh', 'SCHOOL'), ('bảng trắng', 'SCHOOL'),
    ('phấn màu', 'SCHOOL'), ('bút bi', 'SCHOOL'), ('bút dạ quang', 'SCHOOL'),
    ('bút lông', 'SCHOOL'), ('bút chì màu', 'SCHOOL'), ('gọt bút chì', 'SCHOOL'),
    ('tẩy bảng', 'SCHOOL'), ('kẹp giấy', 'SCHOOL'), ('ghim bấm', 'SCHOOL'),
    ('bìa hồ sơ', 'SCHOOL'), ('nhãn vở', 'SCHOOL'), ('sổ tay', 'SCHOOL'),
    ('lịch học', 'SCHOOL'), ('thẻ học sinh', 'SCHOOL'), ('học bổng', 'SCHOOL'),
    ('bằng tốt nghiệp', 'SCHOOL'), ('lễ tốt nghiệp', 'SCHOOL'), ('mũ tốt nghiệp', 'SCHOOL'),
    ('cúp vàng', 'SCHOOL'), ('huy hiệu', 'SCHOOL'), ('chuông vào lớp', 'SCHOOL'),
    ('phòng thí nghiệm', 'SCHOOL'), ('kính hiển vi', 'SCHOOL'), ('ống nghiệm', 'SCHOOL'),
    ('bình tam giác', 'SCHOOL'), ('nam châm', 'SCHOOL'), ('bảng tuần hoàn', 'SCHOOL'),
    ('trái đất mô hình', 'SCHOOL'), ('sa bàn', 'SCHOOL'), ('sách truyện', 'SCHOOL'),
    ('giấy kiểm tra', 'SCHOOL'), ('bài tập về nhà', 'SCHOOL'), ('nhóm học tập', 'SCHOOL'),
    ('lớp học trực tuyến', 'SCHOOL'), ('máy chiếu lớp học', 'SCHOOL'),
    ('căn tin trường', 'SCHOOL'), ('hành lang trường', 'SCHOOL'),

    -- Nhà cửa
    ('mái nhà', 'HOME'), ('ống khói', 'HOME'), ('cánh cửa', 'HOME'),
    ('tay nắm cửa', 'HOME'), ('sàn gỗ', 'HOME'), ('tường gạch', 'HOME'),
    ('giấy dán tường', 'HOME'), ('đèn chùm', 'HOME'), ('đèn ngủ', 'HOME'),
    ('quạt trần', 'HOME'), ('lò sưởi', 'HOME'), ('kệ sách', 'HOME'),
    ('tủ giày', 'HOME'), ('bàn trang điểm', 'HOME'), ('gương đứng', 'HOME'),
    ('mắc áo', 'HOME'), ('giá phơi đồ', 'HOME'), ('máy sấy quần áo', 'HOME'),
    ('bếp nướng', 'HOME'), ('máy xay sinh tố', 'HOME'), ('nồi áp suất', 'HOME'),
    ('chảo rán', 'HOME'), ('thớt', 'HOME'), ('dao bếp', 'HOME'),
    ('khăn tắm', 'HOME'), ('bàn chải đánh răng', 'HOME'), ('kem đánh răng', 'HOME'),
    ('giấy vệ sinh', 'HOME'), ('xà phòng', 'HOME'), ('sọt rác', 'HOME'),
    ('chổi lau nhà', 'HOME'), ('cây lau nhà', 'HOME'), ('máy hút ẩm', 'HOME'),
    ('bình chữa cháy', 'HOME'), ('hộp cứu thương', 'HOME'), ('ổ điện', 'HOME'),
    ('công tắc điện', 'HOME'), ('rèm tắm', 'HOME'), ('bể cá', 'HOME'),
    ('chuồng chim', 'HOME'),

    -- Giải trí
    ('đàn violin', 'ENTERTAINMENT'), ('đàn ukulele', 'ENTERTAINMENT'),
    ('đàn accordion', 'ENTERTAINMENT'), ('kèn trumpet', 'ENTERTAINMENT'),
    ('kèn saxophone', 'ENTERTAINMENT'), ('trống lắc', 'ENTERTAINMENT'),
    ('bàn dj', 'ENTERTAINMENT'), ('micro sân khấu', 'ENTERTAINMENT'),
    ('đèn sân khấu', 'ENTERTAINMENT'), ('mặt nạ hóa trang', 'ENTERTAINMENT'),
    ('trang phục hóa trang', 'ENTERTAINMENT'), ('vương miện đồ chơi', 'ENTERTAINMENT'),
    ('kiếm đồ chơi', 'ENTERTAINMENT'), ('súng nước', 'ENTERTAINMENT'),
    ('máy bay giấy', 'ENTERTAINMENT'), ('máy bay đồ chơi', 'ENTERTAINMENT'),
    ('tàu đồ chơi', 'ENTERTAINMENT'), ('bộ xếp hình lego', 'ENTERTAINMENT'),
    ('khối rubik', 'ENTERTAINMENT'), ('bàn cờ', 'ENTERTAINMENT'),
    ('quân cờ', 'ENTERTAINMENT'), ('xúc xắc', 'ENTERTAINMENT'),
    ('bài tây', 'ENTERTAINMENT'), ('bàn bi lắc', 'ENTERTAINMENT'),
    ('bàn khúc côn cầu', 'ENTERTAINMENT'), ('máy gắp thú', 'ENTERTAINMENT'),
    ('gian hàng hội chợ', 'ENTERTAINMENT'), ('bánh xe đu quay', 'ENTERTAINMENT'),
    ('nhà hơi', 'ENTERTAINMENT'), ('cầu trượt', 'ENTERTAINMENT'),
    ('xích đu', 'ENTERTAINMENT'), ('bập bênh', 'ENTERTAINMENT'),
    ('dây nhảy', 'ENTERTAINMENT'), ('trống trường', 'ENTERTAINMENT'),
    ('đèn pin sân khấu', 'ENTERTAINMENT'), ('màn chiếu', 'ENTERTAINMENT'),
    ('bắp rang bơ', 'ENTERTAINMENT'), ('bút màu nước', 'ENTERTAINMENT'),
    ('sách tô màu', 'ENTERTAINMENT'), ('hộp nhạc', 'ENTERTAINMENT'),

    -- Trang phục
    ('áo hoodie', 'CLOTHING'), ('áo len', 'CLOTHING'), ('áo ba lỗ', 'CLOTHING'),
    ('áo vest', 'CLOTHING'), ('áo blazer', 'CLOTHING'), ('áo choàng', 'CLOTHING'),
    ('áo giáp', 'CLOTHING'), ('áo tạp dề', 'CLOTHING'), ('quần short', 'CLOTHING'),
    ('quần tây', 'CLOTHING'), ('quần yếm', 'CLOTHING'), ('quần legging', 'CLOTHING'),
    ('váy dạ hội', 'CLOTHING'), ('váy xòe', 'CLOTHING'), ('bộ đồ ngủ', 'CLOTHING'),
    ('bộ đồ bơi', 'CLOTHING'), ('bộ đồ thể thao', 'CLOTHING'), ('đồng phục cảnh sát', 'CLOTHING'),
    ('mũ bảo hộ', 'CLOTHING'), ('mũ rộng vành', 'CLOTHING'), ('mũ beret', 'CLOTHING'),
    ('vương miện', 'CLOTHING'), ('băng đô', 'CLOTHING'), ('kẹp tóc', 'CLOTHING'),
    ('khuyên tai', 'CLOTHING'), ('vòng tay', 'CLOTHING'), ('thắt lưng', 'CLOTHING'),
    ('nơ cổ', 'CLOTHING'), ('khăn tay', 'CLOTHING'), ('khăn choàng cổ', 'CLOTHING'),
    ('túi đeo chéo', 'CLOTHING'), ('túi tote', 'CLOTHING'), ('ví cầm tay', 'CLOTHING'),
    ('giày cao gót', 'CLOTHING'), ('giày bốt', 'CLOTHING'), ('giày trượt patin', 'CLOTHING'),
    ('dép lê', 'CLOTHING'), ('găng tay len', 'CLOTHING'), ('vớ sọc', 'CLOTHING'),
    ('đồng hồ cát', 'CLOTHING'),

    -- Việt Nam
    ('bánh mì', 'VIETNAM'), ('phở bò', 'VIETNAM'), ('bún chả', 'VIETNAM'),
    ('cao lầu', 'VIETNAM'), ('cơm hến', 'VIETNAM'), ('bánh bèo', 'VIETNAM'),
    ('bánh ít', 'VIETNAM'), ('nem chua', 'VIETNAM'), ('mắm tôm', 'VIETNAM'),
    ('nước mắm', 'VIETNAM'), ('trà đá', 'VIETNAM'), ('cà phê phin', 'VIETNAM'),
    ('con tò he', 'VIETNAM'), ('đèn ông sao', 'VIETNAM'), ('mặt nạ tuồng', 'VIETNAM'),
    ('múa rối nước', 'VIETNAM'), ('hát quan họ', 'VIETNAM'), ('cồng chiêng', 'VIETNAM'),
    ('trống cơm', 'VIETNAM'), ('lễ hội đua thuyền', 'VIETNAM'), ('chợ nổi', 'VIETNAM'),
    ('cầu Long Biên', 'VIETNAM'), ('hồ Gươm', 'VIETNAM'), ('Văn Miếu', 'VIETNAM'),
    ('Hoàng thành Thăng Long', 'VIETNAM'), ('cố đô Huế', 'VIETNAM'),
    ('ngọ môn', 'VIETNAM'), ('đại nội Huế', 'VIETNAM'), ('chợ Đồng Xuân', 'VIETNAM'),
    ('nhà thờ Đức Bà', 'VIETNAM'), ('bưu điện thành phố', 'VIETNAM'),
    ('dinh Độc Lập', 'VIETNAM'), ('địa đạo Củ Chi', 'VIETNAM'), ('mũi Né', 'VIETNAM'),
    ('đồi cát Mũi Né', 'VIETNAM'), ('đảo Phú Quốc', 'VIETNAM'),
    ('cầu vàng', 'VIETNAM'), ('Bà Nà Hills', 'VIETNAM'), ('tam cốc', 'VIETNAM'),
    ('vườn quốc gia Cúc Phương', 'VIETNAM')
ON CONFLICT (word) DO UPDATE SET category = EXCLUDED.category;
