import { WSRequest } from "./messageTypes";

export function generateRequestId(): string {
  if (typeof crypto !== "undefined" && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  return (
    "req_" + Math.random().toString(36).substring(2, 11) + "_" + Date.now()
  );
}

export function createWSRequest<T>(type: string, payload: T): WSRequest<T> {
  return {
    type,
    requestId: generateRequestId(),
    payload,
  };
}

export const MessageType = {
  // Outbound
  CREATE_ROOM: "CREATE_ROOM",
  JOIN_ROOM: "JOIN_ROOM",
  RESUME_SESSION: "RESUME_SESSION",
  GET_ROOM: "GET_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  START_GAME: "START_GAME",
  GET_GAME_STATE: "GET_GAME_STATE",
  // Phase 2 canvas-recovery contract; backend handling is owned by TV3.
  GET_CANVAS_STATE: "GET_CANVAS_STATE",
  SUBMIT_GUESS: "SUBMIT_GUESS",
  SEND_CHAT: "SEND_CHAT",
  GET_RECENT_CHAT: "GET_RECENT_CHAT",

  SET_READY: "SET_READY",
  REMATCH: "REMATCH",
  KICK_PLAYER: "KICK_PLAYER",
  SET_CATEGORIES: "SET_CATEGORIES",
  SELECT_WORD: "SELECT_WORD",
  SEND_REACTION: "SEND_REACTION",

  // Drawing Outbound (Client → Server)
  DRAW_POINT: "DRAW_POINT",
  DRAW_BATCH: "DRAW_BATCH",
  CLEAR_CANVAS: "CLEAR_CANVAS",

  // Inbound / Broadcast
  ROOM_CREATED: "ROOM_CREATED",
  ROOM_JOINED: "ROOM_JOINED",
  SESSION_RESUMED: "SESSION_RESUMED",
  ROOM_INFO: "ROOM_INFO",
  ROOM_LEFT: "ROOM_LEFT",
  PLAYER_JOINED: "PLAYER_JOINED",
  PLAYER_LEFT: "PLAYER_LEFT",
  GAME_STARTED: "GAME_STARTED",
  GAME_STATE: "GAME_STATE",
  ROUND_STARTED: "ROUND_STARTED",
  ROUND_ENDED: "ROUND_ENDED",
  GAME_ENDED: "GAME_ENDED",
  GAME_FINISHED: "GAME_FINISHED",
  PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
  GUESS_RESULT: "GUESS_RESULT",
  PLAYER_GUESSED_CORRECTLY: "PLAYER_GUESSED_CORRECTLY",
  PLAYER_READY_CHANGED: "PLAYER_READY_CHANGED",
  ROOM_RESET: "ROOM_RESET",
  PLAYER_KICKED: "PLAYER_KICKED",
  ROOM_CATEGORIES_UPDATED: "ROOM_CATEGORIES_UPDATED",
  WORD_SELECTION_STARTED: "WORD_SELECTION_STARTED",
  ROUND_COUNTDOWN_STARTED: "ROUND_COUNTDOWN_STARTED",
  HINT_UPDATED: "HINT_UPDATED",
  ROUND_RECAP_STARTED: "ROUND_RECAP_STARTED",
  REACTION: "REACTION",
  CHAT_MESSAGE: "CHAT_MESSAGE",
  CHAT_HISTORY: "CHAT_HISTORY",
  ERROR: "ERROR",

  // Drawing Inbound (Server → Client broadcast)
  DRAW_EVENT: "DRAW_EVENT",
  DRAW_BATCH_EVENT: "DRAW_BATCH_EVENT",
  CANVAS_CLEARED: "CANVAS_CLEARED",
  SYNC_CANVAS_STATE: "SYNC_CANVAS_STATE",
} as const;
